# Generated by Django 3.2.3 on 2021-05-17 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclination', models.CharField(blank=True, choices=[('committed', 'Empenhada'), ('lazy', 'Preguiçosa')], max_length=15, unique=True)),
                ('reliability', models.CharField(blank=True, choices=[('honest', 'Honesta'), ('dishonest', 'Desonesta')], max_length=15, unique=True)),
                ('nature', models.CharField(blank=True, choices=[('good_nature', 'Boa Indole'), ('bad_nature', 'Má Indole')], max_length=15, unique=True)),
                ('intelligence', models.CharField(blank=True, choices=[('ingenious', 'Engenhosa'), ('fool', 'Tola')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty', models.CharField(blank=True, choices=[('pretty', 'Bela'), ('ugly', 'Feia')], max_length=10, unique=True)),
                ('skin_color', models.CharField(blank=True, choices=[('white', 'Branca'), ('brown', 'Marrom'), ('black', 'Preta')], max_length=10, unique=True)),
                ('haiy_type', models.CharField(blank=True, choices=[('straight', 'Liso'), ('curly', 'Cacheado'), ('coily', 'Crespo')], max_length=15, unique=True)),
                ('facial_trace', models.CharField(blank=True, choices=[('large', 'Traço Largo'), ('thin', 'Traço Fino')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, choices=[('white', 'Branca'), ('black', 'Preta')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stereotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stereotype', models.CharField(blank=True, choices=[('superior_race', 'Raça Superior'), ('inferior_race', 'Raça Inferior')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('intelect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.intelect')),
                ('physical_characteristic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.physicalcharacteristic')),
                ('race', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.Socialrace')),
                ('stereotype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.stereotype')),
            ],
        ),
    ]
