# Generated by Django 3.2.3 on 2021-05-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalcharacteristic',
            old_name='haiy_type',
            new_name='hair_type',
        ),
    ]
