# Generated by Django 3.2.3 on 2021-05-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_alter_candidate_intelect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='physical_characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.physicalcharacteristic'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.socialrace'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stereotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.stereotype'),
        ),
    ]
