# Generated by Django 3.2.3 on 2021-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_auto_20210519_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelect',
            name='inclination',
            field=models.CharField(blank=True, choices=[('committed', 'Empenhada'), ('lazy', 'Preguiçosa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='intelect',
            name='intelligence',
            field=models.CharField(blank=True, choices=[('ingenious', 'Engenhosa'), ('fool', 'Tola')], max_length=15),
        ),
        migrations.AlterField(
            model_name='intelect',
            name='nature',
            field=models.CharField(blank=True, choices=[('good_nature', 'Boa Indole'), ('bad_nature', 'Má Indole')], max_length=15),
        ),
        migrations.AlterField(
            model_name='intelect',
            name='reliability',
            field=models.CharField(blank=True, choices=[('honest', 'Honesta'), ('dishonest', 'Desonesta')], max_length=15),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristic',
            name='beauty',
            field=models.CharField(blank=True, choices=[('pretty', 'Bela'), ('ugly', 'Feia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristic',
            name='facial_trace',
            field=models.CharField(blank=True, choices=[('large', 'Traço Largo'), ('thin', 'Traço Fino')], max_length=15),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristic',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('straight', 'Liso'), ('curly', 'Cacheado'), ('coily', 'Crespo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='physicalcharacteristic',
            name='skin_color',
            field=models.CharField(blank=True, choices=[('white', 'Branca'), ('brown', 'Marrom'), ('black', 'Preta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialrace',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'Branca'), ('black', 'Preta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stereotype',
            name='stereotype',
            field=models.CharField(blank=True, choices=[('superior_race', 'Raça Superior'), ('inferior_race', 'Raça Inferior')], max_length=15),
        ),
    ]
