# Generated by Django 3.2.3 on 2021-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20210519_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
